[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_tokens = "4vjYF5HL4xS6sehyeAGhTGExTomDBKPfTWFS5eHj2aqu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
