[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter_program = "3DRpGvotDMHtXzHahF1jdzYEiYa52cwpQcqGiNPw9vRd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
