[features]
seeds = false
skip-lint = false
[programs.localnet]
counter_program = "7yvcNv9BAHHZYPgDag1YFSLEbXiwBTmVmuE4eArSSEKH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ibukunoluwaakintobi/.config/solana/id.json"

[scripts]
test = "pnpx run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
