[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
close_account_program = "2q4uoWExFAbZjeDe4n3miipsT9bX9vLnkSetCfZYF2VT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
