[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hand = "Cd86dtBUzQKYTFtcB8zDxPRUPCtKPocyetWZSnq6PNxv"
lever = "9aM9w7ozrZwXx9bQHbBx6QjWc6F46tdN9ayt86vt9uLL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
